# Generated by Django 4.1.3 on 2023-02-18 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_task_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.TimeField(default=datetime.time(10, 32, 20, 436274)),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 32, 20, 436274)),
        ),
    ]
